from tkinter import *
from tkinter import messagebox

root=Tk()
root.geometry("500x500")
root.title("Listbox")
root.config(background="lightgreen")
list1=Listbox(height=20,width=50)
firstname=Label(text="first name")
firstname.place(x=10,y=20)
firstname.config(background="white")
fistentry=Entry(relief=SUNKEN)
fistentry.place(x=90,y=20)

Lastname=Label(text="Last Name")
Lastname.place(x=10,y=60)
Lastname.config(background="white")
LastnameEntry=Entry(relief=SUNKEN)
LastnameEntry.place(x=90,y=60)
list1.grid(row=1,column=1)
Genderval=StringVar(root," ")
Gender=Label(text="Gender : ")
Gender.config(background="white")
Gender.place(x=10,y=90)
Male=Radiobutton(text="Male",value="Male",variable=Genderval)
Female=Radiobutton(text="FeMale",value="FeMale",variable=Genderval)
Male.config(background="white")
Male.place(x=90,y=90)
Female.config(background="white")
Female.place(x=160,y=90)
Languages=Label(text="Languages")
Languages.config(background="white")
Languages.place(x=10,y=120)
HindiVar=StringVar(root," ")
Englishvar=StringVar(root," ")
Teluguvar=StringVar(root," ")
Telugu=Checkbutton(text="Telugu",offvalue=0,onvalue=1,variable=Teluguvar)
English=Checkbutton(text="English",offvalue=0,onvalue=1,variable=Englishvar)
Hindi=Checkbutton(text="Hindi",offvalue=0,onvalue=1,variable=HindiVar)
Telugu.place(x=100,y=120)
Telugu.config(background="white")
English.place(x=160,y=120)
English.config(background="white")
Hindi.place(x=220,y=120)
Hindi.config(background="white")
Email=Label(text="Email")
Email.place(x=20,y=170)
Email.config(background="white")
EmailEntry=Entry(relief=SUNKEN)
EmailEntry.place(x=90,y=170)
Address=Label(text="Address : ")
Address.place(x=20,y=200)
Address.config(background="white")

def fetching():
    messagebox.showinfo("Insert","Data inserted successfully")
    fetched.config(text=f"Your name is {fistentry.get()}")
    lastnamefetched.config(text=f"Your last name fetched was {LastnameEntry.get()}")
    Genderfetched.config(text=f"your gender is {Genderval.get()}")
    EmailFetched.config(text=f"your email id is {EmailEntry.get() }")
    lastnamefetched.place(x=400,y=80)
    Genderfetched.place(x=400,y=110)
    EmailFetched.place(x=400,y=140)
def deleting():
    messagebox.showinfo("Delete","Date has been deleted successfully")
    fetched.config(text=" ")
    lastnamefetched.config(text=" ")
    Genderfetched.config(text=" ")
    EmailFetched.config(text=" ")
def Theme():
    messagebox.showinfo("Theme","Theme has been changed successfully")
    BillingRecords.config(background="red")
    list2.config(background="blue")
State=Label(text="State : ")
State.config(background="white")
State.place(x=20,y=240)

AddressEntry=Entry()
AddressEntry.place(x=90,y=200)
zip=Label(text="Zip")
zip.config(background="white")
zip.place(x=20,y=260)
zipEntry=Entry()
zipEntry.place(x=60,y=260)
CreditCard=Label(text="creditCard")
CreditCard.place(x=10,y=290)
CreditCard.config(background="white")
InsertButton=Button(text="Insert",command=fetching)
InsertButton.place(x=320,y=20)
DeleteButton=Button(text="Delete",command=deleting)
DeleteButton.place(x=320,y=80)
ThemeButton=Button(text="Theme",command=Theme)
ThemeButton.place(x=320,y=140)
list2=Listbox(height=20,width=50)
list2.place(x=400,y=0)
BillingRecords=Label(text="BillingRecords")
BillingRecords.config(background="grey")
BillingRecords.place(x=400,y=0,width=302,height=50)
fetched=Label(text=" ")
fetched.place(x=400,y=50)
fetched.config(background="white")
lastnamefetched=Label(text=" ")
lastnamefetched.config(background="white")
lastnamefetched.place(x=400,y=80)
Genderfetched=Label(text=" ")
Genderfetched.config(background="white")
Genderfetched.place(x=400,y=110)
EmailFetched=Label(text=" ")
EmailFetched.config(background="white")
EmailFetched.place(x=400,y=140)
# Fetched=Entry(relief=SUNKEN)
# Fetched.place(x=400,y=50)
root.mainloop()